In [1]:
import numpy as np
import cv2 # opencv library

In [2]:
img = cv2.imread('./images/car_001.jpg') # bgr , # 8 bit

In [3]:
print(img) # 3d (row, col, channel)

[[[120 115 106]
  [ 67  62  53]
  [ 63  57  50]
  ...
  [151 137 125]
  [ 98  92  85]
  [ 59  56  52]]

 [[110 105  96]
  [ 61  56  47]
  [ 67  61  54]
  ...
  [177 165 153]
  [117 111 106]
  [ 84  81  77]]

 [[106  98  91]
  [ 66  58  51]
  [ 73  65  58]
  ...
  [150 138 126]
  [ 82  76  71]
  [ 58  56  55]]

 ...

 [[  6  17  25]
  [ 10  21  29]
  [  1  13  19]
  ...
  [123 126 124]
  [127 128 126]
  [131 132 130]]

 [[  5  14  23]
  [  0   0   7]
  [  0  10  17]
  ...
  [141 146 144]
  [146 151 149]
  [149 154 152]]

 [[  0   8  15]
  [ 17  25  32]
  [ 29  37  44]
  ...
  [143 149 148]
  [141 147 146]
  [141 147 146]]]


In [4]:
img.max()

255

In [5]:
img.min()

0

In [6]:
img.shape

(423, 678, 3)

In [7]:
img1 = cv2.imread('./images/0021.jpg')

In [8]:
type(img1)

numpy.ndarray

# Display

In [9]:
cv2.imshow('orignal image',img)
cv2.waitKey(10000) # this command will the the windows for n milliseconds 
cv2.destroyAllWindows()

2023-11-29 13:30:57.164 Python[41951:1422213] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


In [ ]:
cv2.imshow('orignal image',img)
cv2.waitKey(0) # this command display the windown untill you press x or any keybaord key
cv2.destroyAllWindows()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# img BGR
plt.imshow(img[:,:,[2,1,0]]) # assume that image is in RGB format
plt.show()

# Save Image

In [ ]:
cv2.imwrite('./images/save.png',img)

---